#!/bin/sh
#
# usage:  sslinforeq _filename_
#
# Copyright (c) 2007 Oleksii Tsvietnov, me@vorakl.name
#

[ -z "$1" ] && { echo "usage:  sslinforeq _filename_"; exit 1; }

openssl req -noout -text -in "$1"
