#!/bin/sh
#
# usage:  cd /etc/ssl && sslmakecrl 
#
# Copyright (c) 2007 Oleksii Tsvietnov, me@vorakl.name
#

[ -d ./crl ] || mkdir crl
[ -d ./certs ] || mkdir certs
[ -d ./private ] || mkdir private
[ -d ./req ] || mkdir req
[ -f index.txt ] || touch index.txt
[ -f serial ] || echo "01" > serial

openssl ca -config openssl.cnf -gencrl -out ./crl/crl.pem
